workspace:
  base: /build

pipeline:

  packer:
    detach: true
    image: hashicorp/packer
    environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    commands:
      - echo $VCENTER_SERVER
      - packer build ubuntu2004.json
    var_files:
      - template.json
      - variables.json
