pipeline:
  packer:
    image: appleboy/drone-packer
    template: ubuntu2004.json
    actions: build
    force: true
    environment:
      VCENTER_SERVER:
        from_secret: vcenter_server
      VCENTER_USERNAME:
        from_secret: vcenter_username
      VCENTER_PASSWORD:
        from_secret: vcenter_password
      VSPHERE_DATACENTER:
        from_secret: vsphere_datacenter
      VSPHERE_DATASTORE:
        from_secret: vsphere_datastore
      VSPHERE_CLUSTER:
        from_secret: vsphere_cluster
      VSPHERE_NETWORK:
        from_secret: vsphere_network
    var_files:
      - variables.json
      - template.json
