pipeline:
  test:
    image: hashicorp/packer
    environment:
      VCENTER_SERVER:
        from_secret: vcenter_server
    commands:
      - echo $VCENTER_SERVER
      - make build
      - make test
