kind: pipeline
name: default

steps:
- name: build
  image: hashicorp/packer
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
    VSPHERE_DATACENTER:
      from_secret: vsphere_datacenter
    VSPHERE_CLUSTER:
      from_secret: vsphere_cluster
    VSPHERE_DATASTORE:
      from_secret: vsphere_datastore
    VSPHERE_NETWORK:
      from_secret: vsphere_network
    RESOURCE_POOL:
      from_secret: resource_pool
  commands:
    - packer build --var-file=variables.json -var-file=template.json ubuntu2004.json
