kind: pipeline
name: default

steps:
- name: build
  image: hashicorp/packer
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_server
    VCENTER_USERNAME:  
      from_secret: vcenter_username
    VCENTER_PASSWORD:
      from_secret: vcenter_password
      
  commands:
    - packer build --var-file=variables.json -var-file=template.json ubuntu2004.json
