kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    VCENTER_SERVER:
      from_secret: vcenter_username
    PASSWORD:
      from_secret: vcenter_password
  commands:
    - echo $USERNAME
