pipeline:
     packer:
       image: appleboy/drone-packer
       template: ubuntu2004.json
       actions: build
       force: true
       var_files:
        - variables.json
        - template.json
